<Button>:
	font_size: 40
	color: 0,1,0,1
	size_hint: 0.6, 0.2

<MainWindow>:
	Button:
		text: "Departure Station"
		pos_hint: {'x': 0.2, 'y': 0.7}
		on_release: root.manager.current = 'select_departure_station_window'

	Button:
		text: "Arrival Station"
		pos_hint: {'x': 0.2, 'y': 0.4}
		on_release: root.manager.current = 'select_arrival_station_window'

	Button:
		text: "Start Search"
		pos_hint: {'x': 0.2, 'y': 0.1}
		on_release: root.manager.current = 'list_all_results_window'
